version: '2.1'

services:
  py-clean-arch:
    build: .
    environment:
      DB_CONNECTION: "postgresql://py-user:123456@postgres:5432/py-db"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: "py-user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "py-db"
    ports:
      - "15432:5432"
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/1-migration.sql
      - ./migrations/populate.sql:/docker-entrypoint-initdb.d/2-migration.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
